name: CI        #Workflow の名前何でもOK

on:             #実行されるタイミングを設定
  push:         #pushでマージされた時も動く（pull_request:とすればプルリクのマージのみになる）
    branches:   #対象となるブランチを設定
      - main

jobs:           #以下が実行される内容
  build:
    runs-on: ubuntu-latest  #実行環境を指定

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master    #使用するアクション（sshでサーバに接続）
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |     #サーバで実行されるコマンド（サーバ内で動かせるコマンドなら大体できるはず…なので色々やってみると吉？）
            cd ${{ secrets.SERVER_DEPLOY_DIR }} 
            git pull origin main