name: CI

on:
push:
    branches:
        - main

jobs:
    build:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            port: ${{ secrets.REMOTE_PORT }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
            echo ${{ secrets.REMOTE_PATH }}
            cd ${{ secrets.REMOTE_PATH }}
            git pull origin main
