name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/checkout@latest_version
        with:
          fetch-depth: 0
          persist-credentials: false
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Change directory and pull
        run: |
          cd ${{ secrets.SERVER_DEPLOY_DIR }}
          git pull