name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Change directory and pull
        run: |
          cd /home/c3039616/public_html/pompon-blog.com/test/
          git pull origin main