name: CI for Develop

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory and pull
        run: |
          cd /home/c3039616/public_html/pompon-blog.com/test
          git pull origin main