name: Pull changes to public/test

on:
  push:
    branches:
      - main

jobs:
  pull_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes to public/test
        run: |
          cd public/test
          git pull origin main