name: deploy to ConoHa WING

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete
          path: ${{ github.workspace }}/theme/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}